dist: xenial
cache:
  directories:
    - $HOME/.cache/pip
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -U pip pytest>=3.0.0
  - "pip install -e .[dev]"
script:
  - flake8 valohai_yaml
  - py.test -vvv --cov .
after_success:
  - bash <(curl -s https://codecov.io/bash)
